app.py
#-*- coding: utf-8 -*-

from flask import Flask
from filters import *
from blueprints.admin import admin_api
from blueprints.user import user_api

app = Flask(__name__)

# blueprint 등록
app.register_blueprint(admin_api, url_prefix='/admin')
app.register_blueprint(user_api, url_prefix='')

# jinja2 필터함수 등록
app.jinja_env.filters['datetime'] = format_datetime


if __name__ == '__main__':
    app.secret_key = "123"
    app.run('0.0.0.0', port=5000, debug=True)

blueprints/admin.py
#-*- coding: utf-8 -*-

import json

from flask import Blueprint, render_template, jsonify, request, session, redirect, url_for
from pymongo import MongoClient

from filters import *
from functions import *
from datetime import timedelta
from bson.objectid import ObjectId
import sms

admin_api = Blueprint('admin_api', __name__, template_folder='templates/admin')

# MongoDB 연결
client = MongoClient('localhost', 27017)
db = client.bernini


@admin_api.route('/login', methods=['GET'])
def login():
    if request.args.get('next'):
        next = request.args.get('next')
    else:
        next = "booklist"
    return render_template('admin/login.html', next=next)


@admin_api.route('/booklist', methods=['GET'])
def booklist():
    if not session.get('logged_in'):
        return redirect(url_for('admin_api.login', next=request.full_path))

    today = get_today()

    id = ObjectId(request.args.get('id'))
    status = 3

    if request.args.get('id') is not None:
        bookings = []
        bookings.append(db.booking.find_one({'_id': id}))
    else:
        condition = {'date': {'$gte': today}}

        if request.args.get('status'):
            status = int(request.args.get('status'))
            # status가 0,1,2인 경우만 condition에 추가
            if status < 3:
                condition['status'] = status

        bookings = list(db.booking.find(condition).sort('_id', -1))

    # 예약상태 구하기
    for i in range(len(bookings)):
        if bookings[i]['status'] == 0:
            bookings[i]['status_str'] = "예약신청중"

        elif bookings[i]['status'] == 1:

            if bookings[i]['date'] >= today:
                bookings[i]['status_str'] = "예약승인"
            else:
                bookings[i]['status_str'] = "이용완료"

        elif bookings[i]['status'] == 2:
            bookings[i]['status_str'] = "예약취소"

    return render_template('admin/booklist.html', bookings=bookings, id=request.args.get('id'), status=status)


@admin_api.route('/settingdate')
def settingdate():
    if not session.get('logged_in'):
        return redirect(url_for('admin_api.login', next=request.full_path))

    today = get_today()
    dates = list(db.date.find({'date': {'$gte': today}}).sort('date', 1))

    return render_template('admin/settingdate.html', dates=dates)


@admin_api.route('/datebook', methods=['GET'])
def datebook():
    if not session.get('logged_in'):
        return redirect(url_for('admin_api.login', next=request.full_path))

    if request.args.get('date') is None:
        date = get_today()
        selected_date = datetime.strftime(date, "%Y-%m-%d")
    else:
        selected_date = request.args.get('date')
        date = datetime.strptime(selected_date, "%Y-%m-%d")

    today = get_today()
    dates = list(db.date.find({'date': {'$gte': today}}).sort('date', 1))

    bookings = list(db.booking.find({'date': date, 'status': {'$lte': 1}}).sort('time', 1))

    # 예약상태 구하기
    for i in range(len(bookings)):
        if bookings[i]['status'] == 0:
            bookings[i]['status_str'] = "예약신청중"

        elif bookings[i]['status'] == 1:
            bookings[i]['status_str'] = "예약승인"

    return render_template('admin/datebook.html', bookings=bookings, dates=dates, selected_date=selected_date)


@admin_api.route('/adddate', methods=['POST'])
def adddate():
    start_date = request.form['start_date']
    end_date = request.form['end_date']
    inserted_date = datetime.strptime(start_date, "%Y-%m-%d")
    convert_end_date = datetime.strptime(end_date, "%Y-%m-%d")
    while inserted_date <= convert_end_date:
        # 기존에 있던 날짜가 아닐 때만 insert
        if not db.date.find({'date': inserted_date}).count():
            db.date.insert_one({'date': inserted_date})
        inserted_date += timedelta(days=1)
    return jsonify({'result': 'success'})


@admin_api.route('/deletedate', methods=['POST'])
def deletedate():
    delete_dates = json.loads(request.form['delete_dates'])
    for date in delete_dates:
        date_id = ObjectId(date)
        db.date.remove({'_id': date_id})
    return jsonify({'result': 'success'})


@admin_api.route('/approve', methods=['POST'])
def approve():
    booking_id = ObjectId(request.form['booking_id'])
    db.booking.update_one({'_id': booking_id}, {'$set': {'status': 1}})

    # 예약승인 문자 보내기
    booking = db.booking.find_one({'_id': booking_id}, {'_id': 0, 'name': 1, 'phone': 1, 'date': 1})
    sms.send(booking)

    return jsonify({'result': 'success'})


@admin_api.route('/cancel', methods=['POST'])
def cancel():
    booking_id = ObjectId(request.form['booking_id'])
    db.booking.update_one({'_id': booking_id}, {'$set': {'status': 2}})
    return jsonify({'result': 'success'})


@admin_api.route('/login-chk', methods=['POST'])
def login_chk():
    id = request.form['id']
    password = request.form['password']
    result = db.admin.find_one({'id': id, 'password': password})

    if result is None:
        return jsonify({'result': 'fail'})
    else:
        session['logged_in'] = True
        return jsonify({'result': 'success'})


@admin_api.route('/logout', methods=['POST'])
def logout():
    session['logged_in'] = False
    return jsonify({'result': 'success'})

blueprints/user.py
#-*- coding: utf-8 -*-

from flask import Blueprint, render_template, jsonify, request
from pymongo import MongoClient
from bson.objectid import ObjectId
from filters import *
from functions import *

user_api = Blueprint('user_api', __name__, template_folder='templates')

# MongoDB 연결
client = MongoClient('localhost', 27017)
db = client.bernini


@user_api.route('/')
def home():
    return render_template('user/home.html')


@user_api.route('/book')
def book():
    today = get_today()

    dates = list(db.date.find({'date': {'$gte': today}}, {'_id': 0}).sort("date", 1))
    times = list(db.time.find({}, {'_id': 0}).sort("time", 1))

    return render_template('user/book.html', dates=dates, times=times)


@user_api.route('/chkguest')
def chkguest():
    return render_template('user/chkguest.html')


@user_api.route('/booklist', methods=['POST'])
def booklist():
    name_receive = request.form['name']
    phone_receive = request.form['phone']

    bookings = list(db.booking.find({'name': name_receive, 'phone': phone_receive}).sort("date", -1))

    for i in range(len(bookings)):
        if bookings[i]['status'] == 0:
            bookings[i]['status_str'] = "예약신청중"

        elif bookings[i]['status'] == 1:

            today = get_today()

            if bookings[i]['date'] >= today:
                bookings[i]['status_str'] = "예약승인"
            else:
                bookings[i]['status_str'] = "이용완료"

        elif bookings[i]['status'] == 2:
            bookings[i]['status_str'] = "예약취소"

    return render_template('user/booklist.html', name=name_receive, phone=phone_receive, bookings=bookings)


@user_api.route('/makebook', methods=['POST'])
def makebook():
    date_receive = datetime.strptime(request.form['date'], "%Y-%m-%d")
    time_receive = request.form['time']
    count_receive = int(request.form['count'])
    name_receive = request.form['name']
    phone_receive = request.form['phone']

    db.booking.insert_one(
        {'date': date_receive,
         'time': time_receive,
         'count': count_receive,
         'name': name_receive,
         'phone': phone_receive,
         'status': 0,  # 0: 예약신청중, 1: 예약승인, 2: 예약취소
         })

    return jsonify({'result': 'success'})

@user_api.route('/cancelbook', methods=['POST'])
def cancelbook():
    id = ObjectId(request.form['id'])

    update_result = db.booking.update_one({'_id': id}, {'$set': {'status': 2}}).raw_result

    if update_result:
        result = 'success'
    else:
        result = 'fail'

    return jsonify({'result': result})

templates/layout.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <!-- Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Yellowtail&display=swap" rel="stylesheet">

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>

    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/css.css') }}">

    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- JS -->
    {% block js %}{% endblock %}

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a id="bernini" class="navbar-brand bernini" href="{{ url_for('home') }}">Bernini</a>

    <div class="collapse navbar-collapse" id="navbarColor03">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a id="home" class="nav-link" href="{{ url_for('home') }}">Home</a>
            </li>
            <li class="nav-item dropdown">
                <a id="reservation" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                   aria-haspopup="true"
                   aria-expanded="false">Reservation</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{{ url_for('book') }}">예약하기</a>
                    <a class="dropdown-item" href="{{ url_for('chkguest') }}">예약확인</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

{% block content %}{% endblock %}

<div id="footer" class="align-center">
    <p><small>업체명 : (주)베르니니 ㅣ &nbsp;대표자 : 김셰프<br>
        사업자등록번호 : 000-00-00000<br>주소 : 서울특별시 강남구 언주로152길 15-6<br>
        전화 : 00-0000-0000 &nbsp;ㅣ &nbsp;팩스 : 00-0000-0000<br>
        Copyright (c)bernini. All rights reserved</small></p>
</div>

</body>
</html>

templates/user/book.html
{% extends "user/layout.html" %}

{% block js %}
<script>
    $(document).ready(function(){
  		$("#reservation").addClass("active");
  	});

    function click_book() {
        var pattern = /^01[0-9]-\d{3,4}-\d{4}$/;

        var date = $("#book-date").val()
        var time = $("#book-time").val()
        var count = $("#book-count").val()
        var name = $("#book-name").val()
        var phone = $("#book-phone").val()

  		if (date == "-- 일자를 선택하세요 --") {
  			alert("예약일자를 선택하세요.");
  			$("#book-date").focus();
  		}
  		else if (time == "-- 시간을 선택하세요 --") {
  			alert("예약시간을 선택하세요.");
  			$("#book-time").focus();
  		}
      else if (count == "-- 인원을 선택하세요 --") {
        alert("인원을 선택하세요.");
        $("#book-count").focus();
      }
  		else if (name == "") {
  			alert("예약자명을 입력하세요.");
  			$("#book-name").focus();
  		}
  		else if (phone == "") {
  			alert("연락처를 입력하세요.");
  			$("#book-phone").focus();
  		}
  		else if (phone.match(pattern) == null) {
  			alert("연락처를 형식에 맞게 입력해주세요.");
  			$("#book-phone").focus();
  		}
  		else {
            $.ajax({
                type: "POST",
                url: "/makebook",
                data: { date: date,
                        time: time,
                        count: count,
                        name: name,
                        phone: phone},
                success: function(response){
                    var answer = response.result;
                    if (answer == 'success') {
                        $("#book-form").load(window.location.href + " #book-form");
                        $('.modal').modal('show');
                    }
                }
            })
  		}
  	}

  	function gotoChk() {
  	    window.location.href = "{{ url_for('user_api.chkguest') }}";
  	}
</script>
{% endblock %}

{% block content %}
<!-- Modal -->
<div class="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">예약완료</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>예약이 완료되었습니다.<br>예약승인시 확인문자가 발송됩니다.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" onclick="gotoChk()">예약확인 페이지로</button>
            </div>
        </div>
    </div>
</div>

<div class="wrap" id="book-form">
    <h3 class="custom-title">예약하기</h3>
    <div class="form-group">
        <label for="book-date">예약일자</label>
        <select class="form-control" id="book-date">
            <option selected>-- 일자를 선택하세요 --</option>
            {% for d in dates %}
            <option value="{{ d.date|datetime('%Y-%m-%d') }}">{{ d.date|datetime() }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="book-time">예약시간</label>
        <select class="form-control" id="book-time">
            <option selected>-- 시간을 선택하세요 --</option>
            {% for t in times %}
            <option value="{{ t.time }}">{{ t.time }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="book-count">인원수</label>
        <select class="form-control" id="book-count">
            <option selected>-- 인원을 선택하세요 --</option>
            <option value=2>2명</option>
            <option value=3>3명</option>
            <option value=4>4명</option>
            <option value=5>5명</option>
            <option value=6>6명</option>
        </select>
    </div>
    <div class="form-group">
        <label for="book-name">예약자명</label>
        <input class="form-control" id="book-name">
    </div>
    <div class="form-group">
        <label for="book-phone">연락처</label>
        <input class="form-control" id="book-phone" placeholder="010-0000-0000">
    </div>
    <hr class="mb-4">
    <button type="button" class="btn btn-lg btn-primary btn-block" onclick="click_book()">예약신청</button>
</div>
{% endblock %}

templates/user/booklist.html
{% extends "user/layout.html" %}

{% block js %}
<script>
    $(document).ready(function(){
  		$("#reservation").addClass("active");
  	});

    function click_cancel(id) {

        $.ajax({
            type: "POST",
            url: "/cancelbook",
            data: { id: id },
            success: function(response){
                if (response['result'] == 'success') {
                    $("#myModal").modal('show');
                }
            }
        })
  	}



</script>
{% endblock %}

{% block content %}
<!-- Modal -->
<div class="modal" id="myModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">예약취소</h5>
                <button type="button" class="close" onclick="$('#myModal').modal('hide')">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>예약이 취소되었습니다.</p>
            </div>
            <div class="modal-footer">
                <form action="/booklist" method="post">
                    <input type="hidden" name="name" value="{{ name }}">
                    <input type="hidden" name="phone" value="{{ phone }}">
                    <button type="submit" class="btn btn-secondary">Close</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Content -->
<div class="wrap">
    <h3 class="custom-title">{{ name }}님 예약내역</h3>
    {% for booking in bookings %}
    <div class="card mb-3
    {% if booking.status_str == '예약승인' %} text-white bg-primary
    {% elif booking.status_str == '예약신청중' %} border-primary
    {% else %} bg-light {% endif %}">
        <div class="card-header">{{ booking.status_str }}</div>
        <div class="card-body">
            <div class="row">
                <div class="col-7">
                    <h5 class="card-title">{{ booking.date|datetime() }}</h5>
                    <p class="card-text">시간 {{ booking.time }} | 인원 {{ booking.count }}명</p>
                </div>
                <div class="col-5 right">
                    {% if booking.status_str == '예약승인' or booking.status_str == '예약신청중' %}
                    <form>
                        <button type="button" class="btn btn-secondary" onclick="click_cancel('{{ booking._id }}')">예약취소</button>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/user/chkguest.html
{% extends "user/layout.html" %}

{% block js %}
<script>
    $(document).ready(function(){
  		$("#reservation").addClass("active");

  		$('button').on("click", function(e) {

            e.preventDefault();

            isCorrect = click_chk();
            if(isCorrect == 1) {
                $("form").submit();
            } else {
                return;
            }
  		});
  	});

  	function click_chk() {
        var pattern = /^01[0-9]-\d{3,4}-\d{4}$/;

        var name = $("#book-name").val()
        var phone = $("#book-phone").val()

  		if (name == "") {
  			alert("예약자명을 입력하세요.");
  			$("#book-name").focus();
  			return 0;
  		}
  		else if (phone == "") {
  			alert("연락처를 입력하세요.");
  			$("#book-phone").focus();
  			return 0;
  		}
  		else if (phone.match(pattern) == null) {
  			alert("연락처를 형식에 맞게 입력해주세요.");
  			$("#book-phone").focus();
  			return 0;
  		}
  		else {
  		    return 1;
  		}
  	}
</script>
{% endblock %}

{% block content %}

<div class="small-wrap">
    <h3>예약확인</h3>
    <p class="custom-title">예약정보를 입력해주세요</p>
    <form action="/booklist" method="post">
        <div class="form-group">
            <label for="book-name">예약자명</label>
            <input class="form-control" id="book-name" name="name">
        </div>
        <div class="form-group">
            <label for="book-phone">연락처</label>
            <input class="form-control" id="book-phone" name="phone" placeholder="010-0000-0000">
        </div>
        <hr class="mb-4">
        <button class="btn btn-lg btn-primary btn-block" type="submit">예약조회</button>
    </form>
</div>

{% endblock %}

templates/user/home.html
{% extends "user/layout.html" %}

{% block js %}
<script>
    $(document).ready(function(){
  		$("#home").addClass("active");
  	});

    function gotoBook() {
        window.location.href = "{{ url_for('user_api.book') }}";
    }

</script>
{% endblock %}

{% block content %}
<div class="bg-home">
    <div class="main">
        <img src="{{ url_for('static', filename='media/logo.png') }}" class="logo">
        <p class="align-center" style="color: white; margin-top: 15px; opacity: 50%;">이탈리안 컨템포러리 레스토랑</p>
        <button type="button" class="btn btn-outline-primary btn-lg btn-block" style="margin-top: 40px;"
        onclick="gotoBook()">예약하기</button>
    </div>
</div>
{% endblock %}

templates/user/layout.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Bernini</title>

    <!-- Bootstrap -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/css.css') }}">

    <!-- Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR&display=swap" rel="stylesheet">

    <!-- JS -->
    {% block js %}{% endblock %}

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a id="bernini" class="navbar-brand" href="{{ url_for('user_api.home') }}">
        <img src="{{ url_for('static', filename='media/logo.png') }}" class="sm-logo">
    </a>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor03">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a id="home" class="nav-link" href="{{ url_for('user_api.home') }}">Home</a>
            </li>
            <li class="nav-item dropdown">
                <a id="reservation" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                   aria-haspopup="true"
                   aria-expanded="false">Reservation</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{{ url_for('user_api.book') }}">예약하기</a>
                    <a class="dropdown-item" href="{{ url_for('user_api.chkguest') }}">예약확인</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

{% block content %}{% endblock %}

<div id="footer" class="align-center">
    <p><small>업체명 : (주)베르니니 ㅣ &nbsp;대표자 : 김셰프<br>
        사업자등록번호 : 000-00-00000<br>주소 : 서울특별시 강남구 언주로152길 15-6<br>
        전화 : 00-0000-0000 &nbsp;ㅣ &nbsp;팩스 : 00-0000-0000<br>
        Copyright (c)bernini. All rights reserved</small></p>
    <a href="{{ url_for('admin_api.booklist') }}" class="badge badge-primary">Admin Page</a>
</div>

</body>
</html>